# Generated by Django 5.0.4 on 2024-05-07 18:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_birth', models.DateField(blank=True, null=True)),
                ('date_death', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text_type', models.CharField(choices=[('book', 'Книга'), ('news', 'Новость'), ('wiki', 'Статья'), ('lyrics', 'Текст песни')], max_length=20)),
                ('source', models.CharField(blank=True, max_length=100, null=True)),
                ('year', models.SmallIntegerField(blank=True, null=True)),
                ('pages', models.SmallIntegerField(blank=True, null=True)),
                ('time_to_read', models.SmallIntegerField(blank=True, null=True)),
                ('level', models.CharField(blank=True, choices=[('A1', 'A1 - Начальный'), ('A2', 'A2 - Элементарный'), ('B1', 'B1 - Средний'), ('B2', 'B2 - Выше среднего'), ('C1', 'C1 - Продвинутый'), ('C2', 'C2 - В совершенстве')], max_length=2, null=True)),
                ('language', models.CharField(blank=True, choices=[('RU', 'Русский язык'), ('PL', 'Польский язык')], max_length=2, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('authors', models.ManyToManyField(to='thesis_app.author')),
                ('genres', models.ManyToManyField(to='thesis_app.genre')),
            ],
        ),
        migrations.CreateModel(
            name='TextEditionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edited_on', models.DateTimeField(auto_now_add=True)),
                ('text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thesis_app.text')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
