# Generated by Django 5.0.6 on 2024-05-08 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesis_app', '0002_text_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='texteditionhistory',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
