# Generated by Django 5.0.6 on 2024-05-18 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesis_app', '0004_translatedsentence_translatedtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translatedtoken',
            name='word_translated',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
