# Generated by Django 5.0.6 on 2024-05-19 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesis_app', '0005_alter_translatedtoken_word_translated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='file',
            field=models.TextField(blank=True, null=True),
        ),
    ]
